### ISSUE TITLE
How to handle <default> option in WSS outgoing Signature and Encryption sections

### ISSUE THREAD

**Issue by CuriousQA** [tilln/jmeter-wssecurity#13]
This plugin works well with the encryption and signer for various signature algorithm/canonicalization/digest algorithm in Signature and Symmetric encoding Algorithm/Key encryption algorithm in Encryption sections. when I tried to select <default>, I couldnt get anything. When I edit and use <Default> on the Jmeter plugin for WSS, it is not working. Can you please provide me a solution to this. Thanks and your assistance is much appreciated.
![image](https://user-images.githubusercontent.com/33165402/39839410-a01d205c-53a1-11e8-9543-1324f26a5f6c.png)
![image](https://user-images.githubusercontent.com/33165402/39839483-e2eade56-53a1-11e8-9caa-a110cb862aed.png)
****

**Comment by tilln** [comment]
The initial values of the dropdown boxes in the plugin UI should be the default values as per WSS. Please advise if this is not the case.
It is not necessary to specify default as this is not a recognized value as in SoapUI.

**Comment by tilln** [comment]
Hi @CuriousQA 
Is this still an issue or can this be closed?

**Comment by CuriousQA** [comment]
Apologies for the delayed response.  I tried the initial values but it still doesn't get through the result.

**Comment by tilln** [comment]
I just had a quick look through the [WSS spec](http://www.oasis-open.org/committees/download.php/16790/wss-v1.1-spec-os-SOAPMessageSecurity.pdf) and can't find any default values defined there. 
However, SoapUI's defaults translate to wss4j default values, e.g. for signature:
```
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
```

That doesn't really help resolve your issue I suppose, so let's compare what SoapUI (assuming that works) and this plugin generate.
Perhaps you could provide samples of the wss headers?

**Comment by CuriousQA** [comment]
<ds:Signature Id="SIG-398" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
               <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                  <ec:InclusiveNamespaces PrefixList="soap" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/>
               </ds:CanonicalizationMethod>
               <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
               <ds:Reference URI="#TS-396">
                  <ds:Transforms>
                     <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                        <ec:InclusiveNamespaces PrefixList="wsse soap" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                     </ds:Transform>
                  </ds:Transforms>
                  <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                  <ds:DigestValue>zBVHWCL5dI3dbECjh5jjCDM5VYg=</ds:DigestValue>
               </ds:Reference>
               <ds:Reference URI="#id-397">
                  <ds:Transforms>
                     <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                        <ec:InclusiveNamespaces PrefixList="" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                     </ds:Transform>
                  </ds:Transforms>
                  <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                  <ds:DigestValue>poIW7Y/IpOcjz7a1kIGlhTQjjs0=</ds:DigestValue>
               </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>YAKsBk6THUwMFXrtRr0Q3Hzrfj7qzhIdUZ8WeZW3D0suO46e6twCCPAcfGrvB0Lm58kJspeXeizmduq3LDn9F48lkvRqL1eO3tV1SS01n/4rU8H70WMnm3zyblycjNfV4NkGwpTQznJHSoFDQ8KnMcfAdK3MQsvBZz5FhyIRilQ=</ds:SignatureValue>
            <ds:KeyInfo Id="KI-4B2C50BEB05E6BFD261536604573240318">
               <wsse:SecurityTokenReference wsu:Id="STR-4B2C50BEB05E6BFD261536604573240319">
                  <ds:X509Data>
                     <ds:X509IssuerSerial>
                        <ds:X509IssuerName>CN=service</ds:X509IssuerName>
                        <ds:X509SerialNumber>1380226828</ds:X509SerialNumber>
                     </ds:X509IssuerSerial>
                  </ds:X509Data>
               </wsse:SecurityTokenReference>
            </ds:KeyInfo>
         </ds:Signature>


-_Encryption part
<xenc:EncryptedData Id="ED-4" Type="http://www.w3.org/2001/04/xmlenc#Content" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
			<xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
			<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
				<wsse:SecurityTokenReference wsse11:TokenType="http://docs.oasis-open.org/wss/oasis-wss-soap-message-security-1.1#EncryptedKey" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsse11="http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd">
					<wsse:Reference URI="#EK-9588191B63F746F59615366045725234"/>



I have tried with the above combinations, but didnot work. Appreciate your assistance in this.

**Comment by tilln** [comment]
@CuriousQA 
First of all, the xml tags are not coming through in normal text, so you may want to enclose xml in three backticks ` ``` `

You didn't mention whether your xml is from a (working) SoapUI request or a (failing) Jmeter request.
Can you please clarify and provide both, for comparison.

If you could also provide JMeter log output (start JMeter with command line options `-Lorg.apache.wss4j=DEBUG -Lnz.co.breakpoint=DEBUG`
