### ISSUE TITLE
Timestamp pre-processor not getting signed

### ISSUE THREAD

**Issue by jsalaman** [tilln/jmeter-wssecurity#19]
Hello Guys

Im trying to work with the WS Security plugin but somehow cannot make that Timestamp to get it signed.

So far this is how I have the signer pre-procesor configuration:

![image](https://user-images.githubusercontent.com/18297058/47808075-5fbf5e80-dd1c-11e8-804e-32370ba6e67b.png)

And this is how the Timestamp pre-processor looks like:

![image](https://user-images.githubusercontent.com/18297058/47808122-7665b580-dd1c-11e8-84f0-08cdc1ccd1f6.png)

But no luck, the message remains being sent with only the timestamp as non signed:

![image](https://user-images.githubusercontent.com/18297058/47808186-94cbb100-dd1c-11e8-85e6-a24076430827.png)

Appreciate any advice or whether this is some sort of defect...

Worth mention, I tried also getting rid of UsernameToken and Timestamp pre-processors and adding them as part of the initial request:

![image](https://user-images.githubusercontent.com/18297058/47808395-0ad01800-dd1d-11e8-96d3-5e2ddef12134.png)

But same issue, just the Timestamp not getting signed...

**Comment by tilln** [comment]
Can you please confirm:
1. The order of the preprocessors, in particular that the Timestamp preprocessor comes before the Signature preprocessor in the test plan?
2. What the Timestamp's namespace in the "Parts to Sign" is?
3. Versions of Java, JMeter, this plugin?

It would be helpful for troubleshooting to provide a minimal test plan that reproduces the issue with just a Signature and Timestamp preprocessor, and stripped of any confidential details.
Alternatively a screenshot of the test plan structure and complete request payload before and after processing (as text, not screenshot).

**Comment by jsalaman** [comment]
Hi Till,

Yes, I have the timestamp before the signer pre-processor:

![image](https://user-images.githubusercontent.com/18297058/47817727-352dcf80-dd35-11e8-856d-bf0cd7557871.png)

The namespace Im using is this into the signer:

http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd

So for Java: jdk1.8.0_77
Jmeter: 3.1 r1770033
WSS Plugin: 1.6

Attaching XML request pre- and post.

[pre.txt](https://github.com/tilln/jmeter-wssecurity/files/2536372/pre.txt)
[post.txt](https://github.com/tilln/jmeter-wssecurity/files/2536364/post.txt)

Sorry last edit.. here goes the sample plan (after stripping some info, please rename to jmx):

[SOAP Message Signer Repro.txt](https://github.com/tilln/jmeter-wssecurity/files/2536384/SOAP.Message.Signer.Repro.txt)


Thank you!

**Comment by tilln** [comment]
@jsalaman Thanks for those details.
It looks like there is no `<ds:Signature>` element generated at all (which may not be immediately obvious due to the encrypted data), so I'm guessing there is probably some WSS error in the JMeter log.
I noticed the ECDSA signature algorithm so you may want to make sure you use a matching key.
Could you please attach the relevant log lines and confirm?

**Comment by jsalaman** [comment]
@tilln Thanks for the log tip (and sorry for the delay), looking into the exception everything make sense as the actual service provider is expecting an HMACSHA256 interaction which implies ECDSA - now Im falling into dark waters -

Looking further run into the fact that for HMAC I need a different keystore format **jceks**, so upon creating the new keystore, the plugin seems to stop working as in the log Im seeing the following exception:

`2018/11/05 17:31:50 ERROR - nz.co.breakpoint.jmeter.modifiers.AbstractWSSecurityPreProcessor: Processing failed!  org.apache.wss4j.common.ext.WSSecurityException: Cannot create Crypto class null
Original Exception was org.apache.wss4j.common.ext.WSSecurityException: Failed to load credentials.
Original Exception was java.io.IOException: Invalid keystore format
	at org.apache.wss4j.common.crypto.CryptoFactory.getInstance(CryptoFactory.java:122)
	at org.apache.wss4j.common.crypto.CryptoFactory.getInstance(CryptoFactory.java:78)
	at nz.co.breakpoint.jmeter.modifiers.CryptoWSSecurityPreProcessor.getCrypto(CryptoWSSecurityPreProcessor.java:62)
	at nz.co.breakpoint.jmeter.modifiers.WSSSignaturePreProcessor.build(WSSSignaturePreProcessor.java:76)
	at nz.co.breakpoint.jmeter.modifiers.AbstractWSSecurityPreProcessor.process(AbstractWSSecurityPreProcessor.java:63)
	at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:798)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:453)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:418)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:249)
	at java.lang.Thread.run(Thread.java:748)`

Do the actual plugin support this type of store type, if no, do you happen to know how can I make this sample working by just using regular jks - which from my googling, looks not possible -

Thank you!

**Comment by tilln** [comment]
@jsalaman I'm not sure I understand correctly what you mean by 

> an HMACSHA256 interaction which implies ECDSA

I would have thought that HMAC-SHA256 is symmetric and uses a (pre-shared) secret key whereas ECDSA is asymmetric and uses public/private keys.
(Unless one is used for encrypting and the other for signing.)

In order to provide a symmetric/secret key you would indeed need a **jceks** keystore.
This is not currently supported as the plugin simply has no configuration field for the keystore type, though this could be easily implemented (for example by looking at the file extension), which I'm happy to do.

However, this may not solve your issue, if what you need is actually a signature algorithm that is not currently implemented by this plugin (such as any symmetric ones).

If you could please report back exactly what signature algorithm your service expects and what type of keys you are expected to use?

**Comment by jsalaman** [comment]
@tilln you are right, I was a bit unclear.

For your background the service is technically protected using following policy:
[https://docs.oracle.com/middleware/12212/owsm/security/GUID-A2F4CB58-8692-4AA6-A966-F3773386DB79.htm#OWSMS7439](https://docs.oracle.com/middleware/12212/owsm/security/GUID-A2F4CB58-8692-4AA6-A966-F3773386DB79.htm#OWSMS7439)

Which is expecting a Symm HmacSha256 signature, infact if I try to hit the service with rsa-sha256 setting in the plugin, it complains that expect hmac-sha256.

Perhaps Im reading something wrong on the doc itself, but so far everything tells me that for that policy I would need to play with JCEKS.

Contrary same policy for SHA1 works like a charm as it expects rsa-sha1 signature :/

Hope this explains a bit better, Im new to security stuff so Im still trying to process all of this info.

**Comment by tilln** [comment]
As mentioned earlier, HMAC-SHA256 and other symmetric signature algorithms are not currently implemented, nor is JCEKS as keystore format.

You're welcome to submit a pull request with an implementation.

I recommend looking at [wss4j tests](https://github.com/apache/wss4j/blob/wss4j-2.2.2/ws-security-dom/src/test/java/org/apache/wss4j/dom/message/SymmetricSignatureTest.java#L95) for code examples.

**Comment by tilln** [comment]
@jsalaman 
I've had a closer look at symmetric signatures and created a branch with a quick implementation of HMAC and JCEKS support.
Please check this out: https://github.com/tilln/jmeter-wssecurity/releases/tag/1.7-SNAPSHOT-SYMMETRIC-SIGNATURE
Just make sure that the keystore file extension is jceks and that "Key Identifier Type" is set to "Encrypted Key SHA1" (custom tokens are not implemented).
Mind you, this is not very well tested, so keep an eye on the log for errors.

**Comment by tilln** [comment]
This feature has been merged into master and will be part of the next release.
Until then this snapshot release may be used:
https://github.com/tilln/jmeter-wssecurity/releases/tag/1.7-SNAPSHOT
