### ISSUE TITLE
SOAP Message Decrypter: Failed

### ISSUE THREAD

**Issue by Timo-1979** [tilln/jmeter-wssecurity#20]
The SOAP-Message Decrypter do not decrypt, if the Sym Enc Algo is set to http://www.w3.org/2001/04/xmlenc#rsa-1_5.

The Decryption fail with and this was logged:
```
2018-11-16 15:44:14,656 DEBUG o.a.w.d.u.X509Util: Sym Enc Algo: http://www.w3.org/2001/04/xmlenc#rsa-1_5
2018-11-16 15:44:14,656 DEBUG o.a.w.d.p.EncryptedKeyProcessor: The Key transport method does not match the requirement
2018-11-16 15:44:14,656 ERROR n.c.b.j.m.AbstractWSSecurityPostProcessor: Processing failed! 
```

It cost much amount of time to discover, what is wrong (Checked keyStore, keyStore-Password, PrivateKeyPasswort   many times).

My Research-Result was a update of ws4j changed from accepting by default RSA15KeyTransportAlogorith to deny this - but enabling is only possible by change the code (I found no hint for a property for enabling this).

So I ended in download your SourceCode and modfied this class:
**nz.co.breakpoint.jmeter.modifiers.WSSDecryptionPostProcessor**
```
requestData.setDecCrypto(getCrypto());
requestData.setSigVerCrypto(getCrypto());
requestData.setAllowRSA15KeyTransportAlgorithm(true); // <- Added these Line
WSHandlerResult results = secEngine.processSecurityHeader(document, requestData);
return document;
```

I think that there are three possible solution to solve this problem:

1. allow the RSA15KeyTransportAlgorithm in the Decryption Post Processor
2. Add an Log-Output at ERROR-Level for the first two Log-Entries AND remove the RSA15-Algorithm Option from the SOAP-Message-Encrypter (Field Key Encryption Algorithm). (If I can't decrypt RSA15 I should not have the possibility to encrypt with RSA15)
3. Add an checkbox to the SOAP Message Decrypter to enable the RSA15-Algorithm and add an Log-Output at ERROR-Level for the first two Log-Entries.

**Comment by tilln** [comment]
Thanks for reporting this and for the great level of detail!
Fix (as per suggested option 1.) will be included in the next release.
Meanwhile, the pre-release [1.7-SNAPSHOT](https://github.com/tilln/jmeter-wssecurity/releases/tag/1.7-SNAPSHOT) can be used.

@FackelAB 
If you could please test and report back.

**Comment by Timo-1979** [comment]
Sorry, for the late answer. 
But now I've tested it and it was successfully.

Thanks for the fix.
