### ISSUE TITLE
Add Support for Key Encryption Algorithm = http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p

### ISSUE THREAD

**Issue by kieranmurphy1** [tilln/jmeter-wssecurity#29]
Hi,
I am testing a web service running in Oracle Service Bus / Oracle Weblogic Server. The Web Service uses Oracle Web Services Manager security policy: oracle.wsm.policy.name: oracle/wss10_message_protection_service_policy.
When I configure the Soap Message Encrypter, there is no option for setting the parameter Key Encryption Algorithm = http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p.

![image](https://user-images.githubusercontent.com/50413709/65310015-36523000-db85-11e9-927f-49eee3305381.png)

I get the following error from Oracle Web Services Manager when I try to use a different algorithm e.g. http://www.w3.org/2009/xmlenc11#rsa-oaep:

2019-09-19T10:00:29.601-07:00] [osb_server1] [ERROR] [WSM-00030] [oracle.wsm.resources.security] [tid: [ACTIVE].ExecuteThread: '16' for queue: 
'weblogic.kernel.Default (self-tuning)'] [userId: <anonymous>] [ecid: 60ad4447-d060-4a79-b828-2e2b3eb416ba-00000221,0] [APP: Service Bus Kernel]
 [partition-name: DOMAIN] [tenant-name: GLOBAL] [FlowId: 0000MpATx8UFw000jzwkno1TWYcM00001B] [oracle.wsm.policy.name: oracle/wss10_message_protection_service_policy] 
 The encryption method key wrap algorithms do not match : Expected : http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p, Actual : http://www.w3.org/2009/xmlenc11#rsa-oaep.

It would be great if you could restore the support for Key Encryption Algorithm = http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p. I see it was recently removed.

Thanks, Kieran Murphy
Email:  kieranmu@ie.ibm.com

**Comment by tilln** [comment]
Hi @kieranmurphy1 
Looks like a duplicate of your other issue #28 which I fixed earlier.
You may want to use [1.8-SNAPSHOT](https://github.com/tilln/jmeter-wssecurity/releases/tag/1.8-SNAPSHOT) until the next release.

**Comment by kieranmurphy1** [comment]
Thanks Till,
I did not see the earlier reply.

Best regards
Kieran
