### ISSUE TITLE
UsernameToken & Timestamp

### ISSUE THREAD

**Issue by anthonygauthier** [tilln/jmeter-wssecurity#3]
Hi, 

In my SoapUI project, I have a "Username" and "Timestamp" configurations as part of my WS-Security Configurations. I was wondering if there was any way of reproducing these two configs with your plugin.

Do I need to add a certain native sampler, config, pre-processor, etc ? Or do I simply need to add the XML directly into my raw body request?

I do have Timestamp and UsernameToken with their correct namespaces in my "Parts to Sign"

Thanks a lot

**Comment by tilln** [comment]
Hi, 

I hope I understand correctly what you mean by "two configs". SoapUI can define multiple Outgoing WS-Security Configurations of which you can pick one at test runtime, whereas this plugin just defines one config that always applies.
 
If you simply want two elements included in the signature, you would (as you guessed already) simply add the XML directly into your raw body, e.g.

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <wsu:Timestamp>
                <wsu:Created>${created}</wsu:Created>
                <wsu:Expires>${expires}</wsu:Expires>
            </wsu:Timestamp>
            <wsse:UsernameToken>
                <wsse:Username>${username}</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">${password}</wsse:Password>
            </wsse:UsernameToken>
        </wsse:Security>
    </soapenv:Header>
    <soapenv:Body>
        <your_content_here/>
    </soapenv:Body>
</soapenv:Envelope>
```

Then in your "Parts to Sign" list all elements to be included (just as in SoapUI), e.g.

|Name|Namespace|Encode|
|----|---------|------|
|UsernameToken|http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd | |
|Timestamp|http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd | |

The plugin just picks up the raw request (with variables replaced etc.) and adds the signature, however, you'll have to provide all elements you want in there as it won't generate anything for you but the signature.

HTH

**Comment by anthonygauthier** [comment]
Hi,

Thank you for your detailed response. I will test it out today, but if I correctly understand what you're saying, the plugin will pick up any elements of the signature already present in my raw body request and add/modify the rest of the signature to it?

Thanks again,

**EDIT :** That's exactly what it does - awesome! Thank you! Issue is fixed!

**Comment by delirius325** [comment]
Hi,
The original issue is fixed and the web service I'm accessing now allows the connection to be made. Although, I'm now getting this error coming from my SOAP body request : 

```
2017/06/09 12:09:35 ERROR - nz.co.breakpoint.jmeter.modifiers.AbstractWSSecurityPreProcessor: org.xml.sax.SAXParseException; lineNumber: 52; columnNumber: 93; Invalid byte 1 of 1-byte UTF-8 sequence.
`

Here's the line where it crashes

```
<sch:OrganizationBusinessActivityValue>Oilseed (except Soybean) Farming US</sch:OrganizationBusinessActivityValue>
`

I'm guessing the error is thrown at line 112 of the AbstractWSSecurityPreProcessor class

```
Document doc = docBuilder.parse(new ByteArrayInputStream(xml.getBytes()));
`
