### ISSUE TITLE
WSM-00081: The X.509 certificate is not signed. 

### ISSUE THREAD

**Issue by kieranmurphy1** [tilln/jmeter-wssecurity#31]
Hi, I am trying to use JMeter to test a Web Service which is deployed in Oracle Service Bus (OSB). The web service is secured using Oracle Web Services Manager (OWSM) policy "wss10_x509_token_with_message_protection_service_policy". I am testing the web service in two ways: 
(a) using a Java client with OWSM client libraries. The client is configured to use the OWSM policy "wss10_x509_token_with_message_protection_client_policy". This works.

(b) using JMeter where I get the following error:
WSM-00081: The X.509 certificate is not signed. 
Cause: The X509 token used was not signed according to requirements of certificate authentication scenario.
Action: Sign the X509 token (depending upon the reference mechanism used) for certificate authentication. 

This is the JMeter signer configuration:
![JMeter-Capture-X509](https://user-images.githubusercontent.com/50413709/66712783-be4ce380-ed99-11e9-8bd8-e54cd9c24090.JPG)

I am using the same JKS keystore for each test, so this is not the issue.

I am attaching the SOAP request message for each case:
(a) Java client request message: 
[wss10_x509-Request-Eclipse-SUCCESS.txt](https://github.com/tilln/jmeter-wssecurity/files/3721551/wss10_x509-Request-Eclipse-SUCCESS.txt)

(b) JMeter request message:
[wss10_x509-Request-johnson-JMeter-FAIL.txt](https://github.com/tilln/jmeter-wssecurity/files/3721552/wss10_x509-Request-johnson-JMeter-FAIL.txt)

I have noticed that the following BST Reference element "#BST-BfIWLAzVEEGi7Q9cKEZtpg22 " is included in the working request message Signature element and there is no similar Reference element in the JMeter Signature element for the failed request message:

Working Request Message snippet:
       <dsig:SignedInfo>
          <dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
          <dsig:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
          <dsig:Reference URI="#BST-byZclrMEp8xUp2pL19XhCw22">
            <dsig:Transforms>
              <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            </dsig:Transforms>
            <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <dsig:DigestValue>KR5r6kv0ERYTCLyK3Gk1KU6OhnM=
</dsig:DigestValue>
          </dsig:Reference>
          <dsig:Reference URI="#Timestamp-QHxDiLXj12Nh1Bdc2dvTWg22">
            <dsig:Transforms>
              <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            </dsig:Transforms>
            <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <dsig:DigestValue>+EMaW6GgiNBRHZ6jam53hGyMAZk=
</dsig:DigestValue>
          </dsig:Reference>
          <dsig:Reference URI="#Body-opr0oUmWvnjZ1du1XsjdDg22">
            <dsig:Transforms>
              <dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            </dsig:Transforms>
            <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <dsig:DigestValue>XwKoT4Ub5q8afx8b6znWqzXZ2Fs=
</dsig:DigestValue>
          </dsig:Reference>
        </dsig:SignedInfo>
        <dsig:SignatureValue>X4WYKrjnQ0DTDZyPF5IbntxHrD2GHLiYl2kLs4b6fC6qltsZE2zgozEFHMRceEZv
vzZHeRye+1D0t8/gnZRLUUF/5akZwVBI4RFZWuakSu1yS725foprZ8rP7CeUrij3
R81hZpqTXzPecqIVhcm7+03CaEYZCY3g+YbQDT57fzenessyl6wOLDqoChtkxIYl
AJHIu2ZNVppB76gMj8bZ0vgFR9hm1baS09ROf0mR9AmcTjYlcwtAClcbM1LLGOQY
6CHyStqJ1uoR5OI76fukxj//xLJOISHKRHd3tU+wZvwU7jczAfYB8bEITXmcbmzg
h3b8L5D8AkgPhJ4nxaGcxA==
</dsig:SignatureValue>
        <dsig:KeyInfo xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" Id="KeyInfo-zGFksfYYcrikntWco71d0w22">
          <wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
            <wsse:Reference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" URI="#BST-byZclrMEp8xUp2pL19XhCw22" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/>
          </wsse:SecurityTokenReference>
        </dsig:KeyInfo>
      </dsig:Signature>

Failed Request Message snippet:

     <ds:SignedInfo>
          <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
            <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="hel soapenv"/>
          </ds:CanonicalizationMethod>
          <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
          <ds:Reference URI="#TS-20f4f966-d5d3-4e33-946a-bd081730e356">
            <ds:Transforms>
              <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="hel soapenv wsse"/>
              </ds:Transform>
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <ds:DigestValue>zogmN9dlltiNukTE8AGB4iW+Xaw=</ds:DigestValue>
          </ds:Reference>
          <ds:Reference URI="#id-9df7db44-2071-457b-9d1c-48db860bea46">
            <ds:Transforms>
              <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="hel"/>
              </ds:Transform>
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <ds:DigestValue>afsdiKkgMV4DLY7E0bceAqlNVI4=</ds:DigestValue>
          </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>FqytAAUhim6tGhKA+zsxMOdAulrDZZXONemPHrWxzGS3qUZL61TyEtGDpEs4Ls5i/ONJ+Xq9uPA96d1TQq5V628dpBdtTLcq17/hDFzOb08NqNj5Zlclo5zCYCiIqZkROwIQs/P/oLsamuyNen+jjRfMhPtP0BlsvzuCi2Xkowlms+ArcS+Rhzf5bVRYyRU3YAfbAuMh0g8vCfLt4j4s2q76Wjvu0BptbMndKGOfaz9IlxQUTzo6nyOjYIkqWPz+iSwAb9QNr5I9h44tQ31idZybG1ATTKq7u5b5BvlbVqZitrRkc+uBHzzqDAEBaZ3nhHmDmL/5ycDfGPagGrzcUA==</ds:SignatureValue>
        <ds:KeyInfo Id="KI-cd332575-1f32-4ce2-b708-df8ad7bd5950">
          <wsse:SecurityTokenReference wsu:Id="STR-33f423b7-d739-401e-a6b9-aaa7013327e9">
            <wsse:Reference URI="#X509-b73782ac-77ca-46cf-a193-83d9908c5e87" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/>
          </wsse:SecurityTokenReference>
        </ds:KeyInfo>

Please investigate this at your convenience.
Kieran Murphy

**Comment by tilln** [comment]
Hi @kieranmurphy1 

I'd guess the missing BST signature is causing the policy violation, so please add the below line in the "Parts to Sign" table 

|ID|Name|Namespace|Encode|
|--|----|---------|------|
|  |BinarySecurityToken|http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd | |

Please also make sure you're using at least v1.7 (which added the ability to sign a BST).

**Comment by kieranmurphy1** [comment]
Hi Till,
That works i.e. adding the BST signature.
I now get a valid response with no error.

For some reason the response is not decrypted even though this works in
other similiar tests.
I have configured the decrypter with both the sender and receiver private
keys but no success.

I attach a copy of the response from the web service.

Kieran
(See attached file: wss10_x509-Request-johnson-JMeter-SUCCESS-BST.TXT)

**Comment by kieranmurphy1** [comment]
Here is the log output in debug mode:

2019-10-14 16:58:13,205 INFO o.a.j.t.JMeterThread: Thread finished: Thread
Group-HelloWorldProtection-wss10_X509_token_message_protection 1-1
2019-10-14 16:58:13,205 INFO o.a.j.e.StandardJMeterEngine: Notifying test
listeners of end of test
2019-10-14 16:58:13,205 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false,
*local*)
2019-10-14 16:58:32,109 INFO o.a.j.e.StandardJMeterEngine: Running the
test!
2019-10-14 16:58:32,110 INFO o.a.j.s.SampleEvent: List of sample_variables:
[]
2019-10-14 16:58:32,110 INFO o.a.j.g.u.JMeterMenuBar: setRunning(true,
*local*)
2019-10-14 16:58:32,112 INFO o.a.j.e.StandardJMeterEngine: Starting
ThreadGroup: 1 : Thread
Group-HelloWorldProtection-wss10_X509_token_message_protection-Johnson-Test-3
2019-10-14 16:58:32,112 INFO o.a.j.e.StandardJMeterEngine: Starting 1
threads for group Thread
Group-HelloWorldProtection-wss10_X509_token_message_protection-Johnson-Test-3.
2019-10-14 16:58:32,112 INFO o.a.j.e.StandardJMeterEngine: Thread will
continue on error
2019-10-14 16:58:32,113 INFO o.a.j.t.ThreadGroup: Starting thread group...
number=1 threads=1 ramp-up=1 delayedStart=false
2019-10-14 16:58:32,115 INFO o.a.j.t.ThreadGroup: Started thread group
number 1
2019-10-14 16:58:32,115 INFO o.a.j.e.StandardJMeterEngine: All thread
groups have been started
2019-10-14 16:58:32,122 INFO o.a.j.t.JMeterThread: Thread started: Thread
Group-HelloWorldProtection-wss10_X509_token_message_protection-Johnson-Test-3
 1-1
2019-10-14 16:58:32,201 ERROR n.c.b.j.m.AbstractWSSecurityPostProcessor:
Processing failed!
org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~
[xercesImpl-2.12.0.jar:?]
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~
[xercesImpl-2.12.0.jar:?]
	at
nz.co.breakpoint.jmeter.modifiers.AbstractXMLTestElement.stringToDocument
(AbstractXMLTestElement.java:31) ~[jmeter-wssecurity-1.8-SNAPSHOT.jar:?]
	at
nz.co.breakpoint.jmeter.modifiers.AbstractWSSecurityPostProcessor.process
(AbstractWSSecurityPostProcessor.java:50)
[jmeter-wssecurity-1.8-SNAPSHOT.jar:?]
	at org.apache.jmeter.threads.JMeterThread.runPostProcessors
(JMeterThread.java:925) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage
(JMeterThread.java:564) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.processSampler
(JMeterThread.java:486) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253)
[ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
2019-10-14 16:58:32,201 INFO o.a.j.t.JMeterThread: Thread is done: Thread
Group-HelloWorldProtection-wss10_X509_token_message_protection-Johnson-Test-3
 1-1
2019-10-14 16:58:32,201 INFO o.a.j.t.JMeterThread: Thread finished: Thread
Group-HelloWorldProtection-wss10_X509_token_message_protection-Johnson-Test-3
 1-1
2019-10-14 16:58:32,202 INFO o.a.j.e.StandardJMeterEngine: Notifying test
listeners of end of test
2019-10-14 16:58:32,202 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false,
*local*

----- Forwarded by Kieran Murphy1/Ireland/IBM on 14/10/2019 17:00 -----

From:	Kieran Murphy1/Ireland/IBM
To:	tilln/jmeter-wssecurity <reply
            +AMAUBDPLALH75VBRFL56FIN3WALEHEVBNHHB4LLFZE@reply.github.com>
Cc:	tilln/jmeter-wssecurity <jmeter-wssecurity@noreply.github.com>,
            Mention <mention@noreply.github.com>
Date:	14/10/2019 16:29
Subject:	Re: [EXTERNAL] Re: [tilln/jmeter-wssecurity] WSM-00081: The
            X.509 certificate is not signed.  (#31)


Hi Till,
That works i.e. adding the BST signature.
I now get a valid response with no error.

For some reason the response is not decrypted even though this works in
other similiar tests.
I have configured the decrypter with both the sender and receiver private
keys but no success.

I attach a copy of the response from the web service.

Kieran
[attachment "wss10_x509-Request-johnson-JMeter-SUCCESS-BST.TXT" deleted by
Kieran Murphy1/Ireland/IBM]

**Comment by tilln** [comment]
All I can see is an XML parser error, suggesting the sample result is not well-formed XML:

```
2019-10-14 16:58:32,201 ERROR n.c.b.j.m.AbstractWSSecurityPostProcessor:
Processing failed!
org.xml.sax.SAXParseException: Content is not allowed in prolog.
```

Can you please confirm what exactly the sample result content looks like, and whether it possibly is a multipart response with attachments?

Here is what was sent through:

```
--uuid:b3264dd0-3a77-44dc-b606-73859b7331f1
Content-Type: text/xml; charset=utf-8

<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><env:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" S:mustUnderstand="1"><wsse:BinarySecurityToken xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" wsu:Id="BST-LFS16hb0HLcGHQGlzU42vQ22">MIIEnjCCAoagAwIBAgICAR4wDQYJKoZIhvcNAQELBQAwdDELMAkGA1UEBhMCSUUxDzANBgNVBAgMBkR1YmxpbjEPMA0GA1UEBwwGRHVibGluMRQwEgYDVQQKDAtJcmlzaCBXYXRlcjEMMAoGA1UECwwDQ0EyMR8wHQYDVQQDDBZjZXJ0aWZpY2F0ZTIuYXV0aG9yaXR5MB4XDTE5MTAwNzExMzA0MVoXDTIwMTAxNjExMzA0MVowWzELMAkGA1UEBhMCSUUxDzANBgNVBAgMBkR1YmxpbjEUMBIGA1UECgwLSXJpc2ggV2F0ZXIxCzAJBgNVBAsMAklUMRgwFgYDVQQDDA9pd2RjMnByb2oxc29hMDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDF8mXAHsfKJg/OcKPpshdWjebxUe6YAP9LEL8eT3q6TKf73PTVTnH86kvuy+5Hp52QM86utljupXjZ3v2Dxzx/V0G9NVtFtnsL2Wc8f5fFMUITjwGP4VdLNdvcovrS0YsyFpqn0paZvGN7RywtRtpUArv6D8Y1tzdboQ/HX0++O47xizHu06VC5twCfthrngs/MVbrct8A/szlAIi/d+6J/cOdTERcFT10N4GvPIJJ8/6NAjeAw5uNRiO+1aXDxgWcRO4M155qG1+MA234MPVTxMemiyl5ihi8TXYMN2tCdTKPidrGUplDh23im692KLb7+zJfAL5FLBy80nkZZGlvAgMBAAGjUzBRMB0GA1UdDgQWBBTefdwqeXy/9dxtHJVmGmBrtFqX8DAfBgNVHSMEGDAWgBS1nzMVFUSekiQLM4JTNTf+R5GNvjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCLTeXlMNmWS/e5FLrF+Cjh0VWOslP9FUuyOF3+c3N6cGcfZlHSr7RuYmMLo1CdR+iT+x0mRPOVY70VcOXlx0SV7McESRTUaY+MLYoaxuPfFA4QqCCImuzfrAb7AlBA4UZzSJbwiXJ9x7TdEZ2I1/tyW98v0Q9XM3pIgdX7tmjCn1PSxS/MHjIWL6m2TWoIA8myCUTKnQZXU0P2c03t/nqSv2Cxf4jZtagp76099y39CY+sWToa3jXjSXdwe8+vDqW3nV2MHhayf4dnPsGwbEPrg3IaDXk3EWfjZsqozpCO5NzwqSPOYr5hOWpG2D/gHMBAgdug7yQnTCX6jM9c4CJNeTVU5PQi5s5NBXfQ1AODulNq8ugWJGJzKU60XbHkFGzu3qY6G4l35rSzF2phAZy8brHEK8PWLTMGSrCqc3FtOY+uSfVctzkjtqtBviJgZpoZzM7wUFRWDFjIrrUo/oD4NF3IUnOJa5OX2PRR64RKHbRtSEf6XSPOXr5erNhHgwYgt2k4tTphDT2k9DvdfZsA3U9xO1AoxrdAqlYAMAEGOXbT8iSoho5jbYFrHDuiWKPc645ya8iyUzGId0jYL3UZjukjZUxYVTlS3wef/ghH5zpnqMQ6R4L03B7Ale4ISbfG5eQRbON3FvJJRpBPuO3SeOf5f+aSCdSKTpx+k4yOcg==</wsse:BinarySecurityToken><xenc:EncryptedKey xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"><xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p"><dsig:DigestMethod xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/></xenc:EncryptionMethod><dsig:KeyInfo xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"><wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:Reference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" URI="#BST-LFS16hb0HLcGHQGlzU42vQ22" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/></wsse:SecurityTokenReference></dsig:KeyInfo><xenc:CipherData><xenc:CipherValue>mEvqwFUMPPTEsae/99EFbPcmNjDDNt9o507PiyPWmjY7DCfiVwzycbXIjsCWFJ2MVgsXBfSiwWd2vRKZJofrO3sErCXqd9oRqmdAK4ZkqKrWrbdJlQFCIN5zUnyOHazfESXIiHJpBvFMecHelR0+HOGg6RI/uk8o5fI7RWx1SzoyyIzhPQ/duDameGGBzpiGj2yr6gqcSf4GEVKrA0aC+5vm/t+ggBUcTLyru6NY6Y4BdjrKAMR5hbvYz08h3gqlFw5LFDwrsdv2hncg7BYkOM6vAg4jNm5KKhyPOWgmNTOkF0E0HkOLYfzr1WPlfuw8NpJS2rRhPSEj+u3kDcc77A==</xenc:CipherValue></xenc:CipherData><xenc:ReferenceList><xenc:DataReference URI="#_1s01ymnv6spxJT35WLQyIg22"/></xenc:ReferenceList></xenc:EncryptedKey><wsu:Timestamp xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="Timestamp-MVX9k1DoX1UfOZojoIAFuQ22"><wsu:Created>2019-10-14T14:05:35Z</wsu:Created><wsu:Expires>2019-10-14T14:10:35Z</wsu:Expires></wsu:Timestamp><wsse:BinarySecurityToken xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" wsu:Id="BST-OXD7IjjL5DF3LfJOB4ScUg22">MIIEnjCCAoagAwIBAgICAR4wDQYJKoZIhvcNAQELBQAwdDELMAkGA1UEBhMCSUUxDzANBgNVBAgMBkR1YmxpbjEPMA0GA1UEBwwGRHVibGluMRQwEgYDVQQKDAtJcmlzaCBXYXRlcjEMMAoGA1UECwwDQ0EyMR8wHQYDVQQDDBZjZXJ0aWZpY2F0ZTIuYXV0aG9yaXR5MB4XDTE5MTAwNzExMzA0MVoXDTIwMTAxNjExMzA0MVowWzELMAkGA1UEBhMCSUUxDzANBgNVBAgMBkR1YmxpbjEUMBIGA1UECgwLSXJpc2ggV2F0ZXIxCzAJBgNVBAsMAklUMRgwFgYDVQQDDA9pd2RjMnByb2oxc29hMDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDF8mXAHsfKJg/OcKPpshdWjebxUe6YAP9LEL8eT3q6TKf73PTVTnH86kvuy+5Hp52QM86utljupXjZ3v2Dxzx/V0G9NVtFtnsL2Wc8f5fFMUITjwGP4VdLNdvcovrS0YsyFpqn0paZvGN7RywtRtpUArv6D8Y1tzdboQ/HX0++O47xizHu06VC5twCfthrngs/MVbrct8A/szlAIi/d+6J/cOdTERcFT10N4GvPIJJ8/6NAjeAw5uNRiO+1aXDxgWcRO4M155qG1+MA234MPVTxMemiyl5ihi8TXYMN2tCdTKPidrGUplDh23im692KLb7+zJfAL5FLBy80nkZZGlvAgMBAAGjUzBRMB0GA1UdDgQWBBTefdwqeXy/9dxtHJVmGmBrtFqX8DAfBgNVHSMEGDAWgBS1nzMVFUSekiQLM4JTNTf+R5GNvjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCLTeXlMNmWS/e5FLrF+Cjh0VWOslP9FUuyOF3+c3N6cGcfZlHSr7RuYmMLo1CdR+iT+x0mRPOVY70VcOXlx0SV7McESRTUaY+MLYoaxuPfFA4QqCCImuzfrAb7AlBA4UZzSJbwiXJ9x7TdEZ2I1/tyW98v0Q9XM3pIgdX7tmjCn1PSxS/MHjIWL6m2TWoIA8myCUTKnQZXU0P2c03t/nqSv2Cxf4jZtagp76099y39CY+sWToa3jXjSXdwe8+vDqW3nV2MHhayf4dnPsGwbEPrg3IaDXk3EWfjZsqozpCO5NzwqSPOYr5hOWpG2D/gHMBAgdug7yQnTCX6jM9c4CJNeTVU5PQi5s5NBXfQ1AODulNq8ugWJGJzKU60XbHkFGzu3qY6G4l35rSzF2phAZy8brHEK8PWLTMGSrCqc3FtOY+uSfVctzkjtqtBviJgZpoZzM7wUFRWDFjIrrUo/oD4NF3IUnOJa5OX2PRR64RKHbRtSEf6XSPOXr5erNhHgwYgt2k4tTphDT2k9DvdfZsA3U9xO1AoxrdAqlYAMAEGOXbT8iSoho5jbYFrHDuiWKPc645ya8iyUzGId0jYL3UZjukjZUxYVTlS3wef/ghH5zpnqMQ6R4L03B7Ale4ISbfG5eQRbON3FvJJRpBPuO3SeOf5f+aSCdSKTpx+k4yOcg==</wsse:BinarySecurityToken><dsig:Signature xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"><dsig:SignedInfo><dsig:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><dsig:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><dsig:Reference URI="#BST-OXD7IjjL5DF3LfJOB4ScUg22"><dsig:Transforms><dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></dsig:Transforms><dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><dsig:DigestValue>SlcMqxF6VaCJWSYCFlm18ZsQjFE=</dsig:DigestValue></dsig:Reference><dsig:Reference URI="#Timestamp-MVX9k1DoX1UfOZojoIAFuQ22"><dsig:Transforms><dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></dsig:Transforms><dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><dsig:DigestValue>ZN7Qe5U9EeAS/YBd0zZ+zHqDmOs=</dsig:DigestValue></dsig:Reference><dsig:Reference URI="#Body-HN8aynWyL9ZLEtx5ZFKN2g22"><dsig:Transforms><dsig:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></dsig:Transforms><dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><dsig:DigestValue>RuNOcBVH7UPXEAQ1skBp8VOFaoU=</dsig:DigestValue></dsig:Reference></dsig:SignedInfo><dsig:SignatureValue>JcWi8YcOq4wztlH429LLFJlMAOfG4sbmbuJvsvwqLW1Z9CktoDovWZb5H6j0cwc3qyAjjG1V4BLqHc9xkOWdHq47orxfim5FR8hX8DynKW/w2bjWab2DpRxmSL0PcUrzkAADt6WZ210GDlrKoCGpNzMdm7UFwcISsaS65IMYXyH2jO2vmeZ+9trvKKJKe38ce9Uo85APy2seLhaEpQ2jtms5PnhvuEqSpsBGK7vHydtRh/w/Sce/BOfxmMZD0GNYvgKbSnWswyt7Jtclr7qFHgRRajJxxyqz0JnBL5DAcA/5fOWtDgFIaXxAqtPpuMUztwgcWjM4I9PQz/IwbZptNg==</dsig:SignatureValue><dsig:KeyInfo xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" Id="KeyInfo-K90U8ab8mk5YsX9PEeLyrg22"><wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:Reference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" URI="#BST-OXD7IjjL5DF3LfJOB4ScUg22" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/></wsse:SecurityTokenReference></dsig:KeyInfo></dsig:Signature></wsse:Security></env:Header><S:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="Body-HN8aynWyL9ZLEtx5ZFKN2g22"><xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Type="http://www.w3.org/2001/04/xmlenc#Content" Id="_1s01ymnv6spxJT35WLQyIg22"><xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/><xenc:CipherData><xenc:CipherValue>eIxV+DBA21aN5ezB2N7RrO+GeRSvlzeGGuORubhdazfwREFMKrNKArhUF7LJwCeveBrE1Vz6puixT78EP3NiAU2FyRCsCq27ou/wNHJwlgx4lj9tXBvWrU7t03GQuvJO8FYNYrwWLPwbGvl7Xu7HLIz9mdVgs/TjBU0T+V/TtejXqpeQFzlP4BuF4mFBrbd+kAP3w4Cec20Owf8CjeceBp8OOZ5jc73ub6Q2gxRy6WAdEID4UhRIMuJUEPg7UUptAf42GbawsjphsBs9B4xKgTqOeZCTh+8ljALJXziR5MyTTddMtCDVzB1wYqnulLFJGwHeulrUS7LsRVK2as6eXnyRoiqtP1DZeRUWAfhjzdf6N6zOtBZxCfPZYPV3CAWstGUcpyVCsUVXY7KTmxe8OeSg2I0qnA0zcmy50LYa2LXFZ3//SgrWg/oUX2+KQt6MHgHaV7jpA9876hE2RVvQAvMAk3t/IWfLN8AHD9mPJJ7GE0IE04F0bGB9daIWj5KP</xenc:CipherValue></xenc:CipherData></xenc:EncryptedData></S:Body></S:Envelope>
--uuid:b3264dd0-3a77-44dc-b606-73859b7331f1
Content-Id:<24b9601e-2680-4ec8-b963-daf5d8aa7abb>
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary
Content-Transfer-Encoding: binary

xUø0@ÛVåìÁØÞÑ¬ïy¯7ã¹¸]k7ðDAL*³J¸T²ÉÀ'¯xÄÕ\ú¦è±O¿?sbMÉ¬
­»¢ïð4rpx?m\Ö­NíÓqºòNðV
b¼,üù{^îÇ,ýÕ`³ôãMù_Óµè×ª9OàâaA­·~÷ÃsmÁÿç9cs½îo¤6ré`øRH2âTø;QJmþ6¶°²:a°=J:yï%É_8äÌM×L´ ÕÌpb©î±IÞºZÔK²ìER¶jÎ^|¢*­?PÙyøcÍ×ú7¬Î´q óÙ`õw¬´e§%B±EWc²¼9ä Ø*
3rl¹Ð¶ØµÅgÿJ
Öú_oBÞÚW¸éß;ê6E[Ðó 
```

However, the `Content-Id:<24b9601e-2680-4ec8-b963-daf5d8aa7abb>` is not referenced in the SOAP message.
