### ISSUE TITLE
Final request not signed

### ISSUE THREAD

**Issue by g-garciac** [tilln/jmeter-wssecurity#34]
Hi, I tried to create a Test to send a SOAP request signed, but I get the error: 

> _Invalid keystore format._

I am using:

- JMeter 5.2.1
- jmeter-wssecurity-1.7.jar
- java version "1.8.0_261"

All of them running on Windows.

The Body data (before the Pre processor) is:
```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <SomeItem>
            <otherItem>
                <AnId>d1b32e62-7056-4edc-8c20-0cc033763c8a</AnId>
            </otherItem>
        </SomeItem>
    </s:Body>
</s:Envelope>
```
The request body (after the Pre processor) is:
```
<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
            xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" s:mustUnderstand="1">
            <wsu:Timestamp wsu:Id="TS-bfd48433-89a0-4ede-9306-2e12ac883e69">
                <wsu:Created>2020-08-01T02:21:50.444Z</wsu:Created>
                <wsu:Expires>2020-08-01T02:26:50.444Z</wsu:Expires>
            </wsu:Timestamp>
        </wsse:Security>
    </s:Header>
    <s:Body>
        <SomeItem>
            <otherItem>
                <AnId>d1b32e62-7056-4edc-8c20-0cc033763c8a</AnId>
            </otherItem>
        </SomeItem>
    </s:Body>
</s:Envelope>
```
**That is: The `Signature` node is not created!**

I am using a Selfsigned certificate created with the ssl commands:
```
openssl genrsa 2048 > private.key
openssl req -new -x509 -nodes -sha1 -days 1000 -key private.key > public.cer
openssl pkcs12 -export -in public.cer -inkey private.key -out cert_key.p12
```
Then the .p12 file is stored in a jks file with:
`keytool -importkeystore -srckeystore cert_key.p12 -srcstoretype PKCS12 -srcstorepass abc123 -keystore mykeystore.jks -storepass abc123`

The configuration for the SOAP Message Signer is:

![image](https://user-images.githubusercontent.com/5044050/89092743-1c26d800-d37a-11ea-9aba-0ee7268eacc1.png)

For better clarity I am attached the inputs used.

[inputs.zip](https://github.com/tilln/jmeter-wssecurity/files/5009764/inputs.zip)

**Comment by tilln** [comment]
Hi @g-garciac 
The keystore type this plugin currently uses is JCEKS (which I had thought would already support PKCS12 but that's apparently not the case). The type could be made configurable, e.g. most easily via a JMeter property.

However, in your case it is probably easiest to just change the keystore type via adding `-deststoretype JCEKS` to your `keytool` command line.
