### ISSUE TITLE
Can we call this security jar files using maven.

### ISSUE THREAD

**Issue by rakeshjk** [tilln/jmeter-wssecurity#38]
Can we call this security jar files using maven, currently i am not able to find the artifact id for this plugin.
Can you please let me know the maven dependency code for this artifact.

**Comment by tilln** [comment]
This has now been published to the Central Repository.

https://search.maven.org/remotecontent?filepath=nz/co/breakpoint/jmeter-wssecurity/1.8/jmeter-wssecurity-1.8.jar

```xml
<dependency>
    <groupId>nz.co.breakpoint</groupId>
    <artifactId>jmeter-wssecurity</artifactId>
    <version>1.8</version>
</dependency>
```
