### ISSUE TITLE
Webservice security version

### ISSUE THREAD

**Issue by Saviour** [tilln/jmeter-wssecurity#39]
Hi @tilln , Hope you are well.

Thanks for this awesome plugin. I am able to sign/encrypt the soap message with ease.

But what if the webservice uses a specific security version 'https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.messagesecurityversion?view=dotnet-plat-ext-6.0'. It works like a charm in loadrunner by selecting the correct security version. When it comes to jmeter, I couldnt find an option to select a similar security version.  or  java doesn't support something similar?

Any thoughts ? 

Thanks,
Saviour

**Comment by tilln** [comment]
Hi @Saviour 

I'm assuming this security version you mention is [.NET specific](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.messagesecurityversion.wssecurity10wstrust13wssecureconversation13wssecuritypolicy12basicsecurityprofile10?view=netframework-4.8) and defines, at a higher level, how the messages are to be secured.

There are Java libraries that support something similar, e.g. Apache [CXF](https://cxf.apache.org/docs/ws-support.html) or [Rampart](https://axis.apache.org/axis2/java/rampart/).

However, this plugin does not currently allow any policy-based configuration, so I'm afraid you'll have to pick apart the security version your web service requires and configure the policy parts manually, one by one, in JMeter.

> I am able to sign/encrypt the soap message with ease.

Sounds like you don't have an issue, but it's just a matter of convenience?

Let me know if you have suggestion for how this could be implemented and what it could look like or perhaps you would want to contribute some implementation yourself?

**Comment by Saviour** [comment]
hi @tilln  thanks for your response. Even though I can send the encrypted message, the request fails to process as the policy doesn't match. Seems like this can be supported only from a .net platform. Cant find anything similar in java.

**Comment by tilln** [comment]
@Saviour 
I can't think of a reason why you would not be able to build correctly formed SOAP requests with JMeter/Java, though it may not be as easy as with LoadRunner/.NET.

If you have a requirement or desire to use JMeter, I'm happy to help make it work with this plugin.

For this I would need ideally all of the below:
- the SOAP "input" message without any security headers/encryption/signatures,
- your JMeter script (or relevant fragment),
- a working request, e.g. from LoadRunner, 
- a rejected request from JMeter,
- rejection error message details.

Where data is encrypted at an element level, please provide a description of what is to be encrypted.
Feel free to use dummy data or redact any sensitive data.

**Comment by Saviour** [comment]
Thanks @tilln . Yes the requirement is to use Jmeter.

But I can't share the requested details with you am afraid :( as it is against my company policy. I really appreciate your inputs.

**Comment by tilln** [comment]
@Saviour 
Unless you can think of another way to provide more details in line with your company policy I can't help you I'm afraid, so this issue may be closed?

**Comment by Saviour** [comment]
Sure. I understand. Thanks again for the help.
