### ISSUE TITLE
UTF-8 Encoding - Sampler parsing

### ISSUE THREAD

**Issue by anthonygauthier** [tilln/jmeter-wssecurity#4]
I'm getting this error coming from my SOAP body request : 

```
2017/06/09 12:09:35 ERROR - nz.co.breakpoint.jmeter.modifiers.AbstractWSSecurityPreProcessor: org.xml.sax.SAXParseException; lineNumber: 52; columnNumber: 93; Invalid byte 1 of 1-byte UTF-8 sequence.
```

Here's the line where it crashes

```xml
<sch:OrganizationBusinessActivityValue>Oilseed (except Soybean) Farming US</sch:OrganizationBusinessActivityValue>
```

I'm guessing the error is thrown at line 116 of the AbstractWSSecurityPreProcessor class

```java
Document doc = docBuilder.parse(new ByteArrayInputStream(xml.getBytes()));
```

## Possible fix : 

```java
Document doc = docBuilder.parse(new ByteArrayInputStream(xml.getBytes("UTF-8")));
```

**Comment by anthonygauthier** [comment]
Issue fixed with this little workaround in a preprocessor script that is executed before the SOAP Message Signer : 

```java
byte[] utf8Bytes = bodyRequest.getBytes("UTF-8");
sampler.getArguments().getArgument(0).setValue(new String(utf8Bytes));
```

The possible fix is the solution, created pull request to implement fix.

**Comment by tilln** [comment]
@delirius325 [Here](https://github.com/tilln/jmeter-wssecurity/releases/download/1.3-SNAPSHOT/jmeter-wssecurity-1.3-SNAPSHOT.jar) is a pre-release for you. Could you please test and confirm if this is fixed?

As a work-around, it should help to set the environment variable 
`JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8`
before starting JMeter.

**Comment by anthonygauthier** [comment]
@tilln The pre-release effectively fixed the issue, thanks! :)
