### ISSUE TITLE
saml2:Assertion

### ISSUE THREAD

**Issue by suneelkumaryaram** [tilln/jmeter-wssecurity#40]
Hello, 

I would like to a webservice using WSS security and saml2:Assertion , how could I do this using plugin, if this is not possible would you recommend me another plugin?

**Comment by tilln** [comment]
Hi @suneelkumaryaram 

This is difficult to answer without knowing more about the contents of your request messages, such as what parts are to be signed or encrypted, and where the SAML assertion comes into play.

Generally, this plugin supports signing/encrypting WSS elements of the webservice request message, but not the signing of the SAML assertion itself. This should be possible though with some custom code e.g. inside a JSR223 Preprocessor. Then the Assertion can be stored in a JMeter variable which can be embedded in the payload so that this plugin could do any additional signature/encryption operation, as per your WSS requirements.

**Comment by suneelkumaryaram** [comment]
Hi @tilln 

Thank you so much for your response below is my request.

`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
<soapenv:Header>
<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
<wsu:Timestamp wsu:Id="TS-9BDCC9B1419A518F1916231428261687">
<wsu:Created>2022-12-20T07:18:01.34Z</wsu:Created>
<wsu:Expires>2022-12-20T07:20:01.34Z</wsu:Expires>
</wsu:Timestamp>
<saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="ife4403ee-bd0c-4734-937e-002d9d306fdb" IssueInstant="2022-12-20T07:17:51Z" Version="2.0">
<saml2:Issuer>vaule</saml2:Issuer>
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
<ds:Reference URI="#ife4403ee-bd0c-4734-937e-002d9d306fdb">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
<ds:DigestValue>TMNdZacvmp+PiH8duRHvD0vw75TGh6WvGlAO4D0CHAg=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>binary content of signature</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>binary content of certificate</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature>
<saml2:Subject>
<saml2:NameID>name</saml2:NameID>
<saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"/>
</saml2:Subject>
<saml2:Conditions NotBefore="2022-12-20T07:17:51Z" NotOnOrAfter="2022-12-20T17:18:01Z"/>
<saml2:AuthnStatement AuthnInstant="2022-12-20T07:17:51Z" SessionIndex="s3cdaba6a-f6df-4c57-8490-9b6f0bee2f99" SessionNotOnOrAfter="2022-12-20T17:18:01Z">
<saml2:AuthnContext>
<saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:unspecified</saml2:AuthnContextClassRef>
</saml2:AuthnContext>
</saml2:AuthnStatement>
</saml2:Assertion>
</wsse:Security>
</soapenv:Header>
<soapenv:Body>
<tns19:searchPartnerRequest>
<tns19:suchbedingungen>
<tns26:searchDate xsi:type="tns25:WsBusinessDateNextBestType">
<tns25:businessDate>2022-12-20+01:00</tns25:businessDate>
</tns26:searchDate>
<tns26:fetchStart>0</tns26:fetchStart>
<tns26:maxFetchSize>500</tns26:maxFetchSize>
</tns19:suchbedingungen>
<tns19:partneridentifikatoren>
<tns19:partneridentifikatorDefId>
<tns9:id>SYR_Partner_PartnerNr</tns9:id>
</tns19:partneridentifikatorDefId>
<tns19:wert>
<tns26:string>9999999</tns26:string>
<tns26:operator>eq</tns26:operator>
</tns19:wert>
</tns19:partneridentifikatoren>
</tns19:searchPartnerRequest>
</soapenv:Body>
</soapenv:Envelope>
`

**Comment by tilln** [comment]
Actually, there's no need for you to use this plugin as there are no signed or encrypted WSS elements in your request header, but only the signed Assertion.
This you can sign with a few lines of code which a bit of googling will let you find.
