### ISSUE TITLE
Java code to implement just the SOAP message signer part of this plugin

### ISSUE THREAD

**Issue by sudheesh1989** [tilln/jmeter-wssecurity#7]
Hi Tilln,

This plugin has been extremely useful to me and many others who use Jmeter to test signed soap requests. I tried looking at the source code but as I'm not an expert with java, couldn't really make out the logic or the code to accomplish just the 'soap message signer' part of this plugin. Reason for looking for this is, I am trying to do similar test in another tool which obviously can't use a jmeter plugin. I think if I pass on the soap packet and call a 'single java file', I would be able to successfully send a signed soap request just like what happens when we use this plugin in jmeter.

Thanks!

**Comment by tilln** [comment]
@sudheesh1989 
There is not much logic there, as this plugin just makes use of [wss4j](https://ws.apache.org/wss4j/using.html) functionality.
What tool are you using?

**Comment by sudheesh1989** [comment]
@tilln - I'm using different tools to try and do the same thing. Currently working on a tool called silk performer. I'm not much aware of this wss4j functionality either which is making it very difficult for me to sign a soap request. I'm able to execute the signed soap request using your plugin. Now I'm trying to do the same thing on this tool. I recorded the signed soap request but it contains hardcoded values which obviously need to be correlated for the request to be successfully signed and executed. Can you give me a piece of java code which will accept an unsigned soap request as input and sign it i.e. attach the signature values and timestamps and return a fully signed soap request valid for next 5 minutes (created and expires timestamp) as output which can be executed successfully just like what soap message signer does in jmeter?

**Comment by tilln** [comment]
@sudheesh1989 
I'm sorry, but I don't have the time to write your code for you.
However, I'm sure with a bit of googling you'll find something suitable.
For example, have a look at https://sourceforge.net/projects/signsoaprequest/

**Comment by sudheesh1989** [comment]
@tilln
Already checked that link and few others but couldn't find anything suitable, hence thought of  checking with you if its feasible. Thank you for the help though!

**Comment by anthonygauthier** [comment]
Hi @sudheesh1989, Silk Performer is a proprietary software from Micro Focus (who also owns HP). Your best bet is probably to look at the tool's doc.

http://documentation.microfocus.com/help/index.jsp?topic=%2Fcom.microfocus.silkperformer.doc%2FSILKPERF-74287FB4-TESTINGSOAP-HTTPBASEDWEBSERVS-CON.html

Otherwise, you can always contact Micro Focus.

**Comment by CuriousQA** [comment]
Thanks for sharing this plugin. This plugin works well with the encryption and signer. Wondering, if we we have similar plugin for the decryption as well. So far I could able to see the successful response from the server through Jmeter, but couldnt verify the response as it is in encrypted format. Your comments are much appreciated.
Thanks 
![1](https://user-images.githubusercontent.com/33165402/32125681-c1518090-bb32-11e7-9dfe-971d7788779c.png)
![2](https://user-images.githubusercontent.com/33165402/32125682-c162896c-bb32-11e7-965c-a9e99cd46e9d.png)

**Comment by tilln** [comment]
@CuriousQA Can you please open a separate issue? Check out [1.4-SNAPSHOT](https://github.com/tilln/jmeter-wssecurity/releases/tag/1.4-SNAPSHOT) which includes a post processor "SOAP Message Decrypter", and let me know how you get on.

**Comment by CuriousQA** [comment]
A separate issue has been created as per the suggestion from @tilln
